on:
  workflow_dispatch:

jobs:
  live-streaming:
    runs-on: ubuntu-latest

    steps:
      - name: install ffmpeg
        run: sudo apt install ffmpeg -y -qq > /dev/null
      - name: id pwd uname
        run: id;pwd;uname -a;ls -al
      - name: live stream
        run: ffmpeg -hide_banner -loglevel error -re -user_agent "Mozilla/5.0" -i "https://token-media-001-vidio-com.vidiocdn.net/uploads/8244825/edge-cache-token=Expires=1720818486&KeyName=tokenized-media-vidio-com-keyset&Signature=d4TW927ahoAXkcAPIfrNdiA0awt6iN8GmcvufLLg2UlaZtfNIbv3H1hq28LH_Rn7owpW1qWoASre-wdCs0fYBA==/etsvod_ETS2d1f79dcd707b67f8_premier.m3u8" -c copy -f flv rtmps://fa723fc1b171.global-contribute.live-video.net:443/app/sk_us-west-2_xFRVgfONJY7d_jWpOnJNiy39EYsXoEXsAyu7i7UxDlA
