on:
  workflow_dispatch:

jobs:
  live-streaming:
    runs-on: ubuntu-latest

    steps:
      - name: install ffmpeg
        run: sudo apt install ffmpeg -y -qq > /dev/null
      - name: id pwd uname
        run: id;pwd;uname -a;ls -al
      - name: live stream
        run: ffmpeg -hide_banner -loglevel error -user_agent "Mozilla/5.0" -i "https://etslive-v3-vidio-com-tokenized.akamaized.net/hls-p/ingest_17252_1080p/hdntl=exp=1720882848~acl=%2f*~id=allUsers~data=hdntl~hmac=693f40348001d0b94bb4acd4de1b05d4a2493faf7d2c1f738d3935a8d41686fc/index.m3u8" -c copy -f flv rtmps://live-api-s.facebook.com:443/rtmp/FB-10231937304523265-0-Abyo080TeZuNW6Hf
        
