name: SSH Tunnel
on: push

jobs:
  deploy:
    name: Set up tunnel
    runs-on: ubuntu-20.04
    steps:
    - name: install ngrock
      run: curl -sO https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz;tar -zxvf ngrok-v3-stable-linux-amd64.tgz
    - name: Add ~/.ssh directory
      run: mkdir -p ~/.ssh
      shell: bash
    - name: Add SSH public key to authorized_keys
      run: echo "${{ inputs.ssh_public_key }}" >> ~/.ssh/authorized_keys
      shell: bash
    - name: Fix home directory permissions
      run: chmod 755 ~
      shell: bash
    - run: chmod 600 ~/.ssh/authorized_keys
      shell: bash
    - name: Set ngrok auth token
      run: ./ngrok authtoken ${{ inputs.ngrok_token }}
      shell: bash
    - name: Debug message
      run: echo "Starting ngrok tunnel..."
      shell: bash
    - name: Setup ngrok tunnel
      run: timeout ${{ inputs.timeout }} ./ngrok tcp ${{ inputs.port }}
      shell: bash
