on:
  workflow_dispatch:

jobs:
  live-streaming:
    runs-on: ubuntu-latest

    steps:
            - name: SSH4Me
  # You may pin to the exact commit or the version.
  # uses: Jisan09/SSH4Me@2bf0f8fe2a8a2f4be275e2332b9e60056169767b
  uses: Jisan09/SSH4Me@1.0.0
          
